### ISSUE TITLE
add '/node_modules/.bin' to the path for executing local commands

### ISSUE THREAD

**Issue by pflannery** [sindresorhus/grunt-shell#101]
Was wondering if we could do this? would then be similar to `npm run`.

```js
  process.env.path += [
    process.platform === 'win32' ? ';' : ':',
    path.join(process.cwd(),'node_modules/.bin')
  ].join('');
```

**Comment by sindresorhus** [comment]
Sure. Sounds like a good addition. Best to make it an option that is `false` by default as I don't want to do more breaking changes to this module. Option name `preferLocal`. Should use https://github.com/sindresorhus/npm-run-path. PR welcome :)
