### ISSUE TITLE
time for esm

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/grunt-shell#124]

**Comment by sindresorhus** [comment]
I already told you multiple times. There's no point in opening issues like these. I plan to do all my packages. I have a list, so I won't miss any. :)

**Comment by jimmywarting** [comment]
>  I have a list

Oh :D 
mind sharing that list? :)

**Comment by sindresorhus** [comment]
My remaining packages: https://gist.github.com/sindresorhus/4752e183d1434ad37d589136ed492f22 (don't open any issues)

Many of them are blocked by JSON support in ESM.
