### ISSUE TITLE
stdout colour 

### ISSUE THREAD

**Issue by OliverJAsh** [sindresorhus/grunt-shell#21]
When I run a command usually, the output has colour. If I run it through `grunt-shell` with the `stdout` flag set, the colour isn't there…

**Comment by DmitryGonchar** [comment]
thanks to the [comment](https://github.com/sindresorhus/grunt-shell/issues/21#issuecomment-14359832) above, I fixed it by adding `--colors` option to my command

**Comment by Giacom** [comment]
I fixed this by adding 

```javscript
options: {
    stdio: "inherit"
}
```

To my config. E.g:

```javascript
grunt.initConfig({
      exec: {
          printColour: {
              command: "print-colour text to print",
              options: {
                  stdio: "inherit"
              }
          }
      }
});
```
