### ISSUE TITLE
async executing / don't wait for command to finish

### ISSUE THREAD

**Issue by cri5ti** [sindresorhus/grunt-shell#5]
Hi there,

Just wanted to let you know I forked your project (here [grunt-shell-spawn](https://github.com/cri5ti/grunt-shell-spawn)) to add support for launching a command asynchronously.

Ideally I wanted to just add an `async: true` property but got too lazy into parsing the arguments as required for child-process.spawn. Plus there are a few minor differences on how they are handled, so I just created the new task `spawn`.

Do you think this would be an interesting feature to add to grunt-shell?

**Comment by soberteq** [comment]
"Is there any chance of merging the async option into grunt-shell?"

+1
