### ISSUE TITLE
stdout doesn't work

### ISSUE THREAD

**Issue by Thinkscape** [sindresorhus/grunt-shell#58]
I haven't debugged it thoroughly, but it's broken.

The command I used was `phonegap build ios`. 

``` js
{
    exec: {
      'phonegap-build-ios' : {
        command    : 'phonegap build ios',
        stdout     : true,
        stderr     : true,
        failOnError: true
      }
    },
    // ...
}
```

No output was displayed regardless of `stdout` or `stderr` settings. What is see is:

```
$ grunt shell:phonegap-build-ios
Running "shell:phonegap-build-ios" (shell) task



Done, without errors.
```

You can get phonegap through NPM to test it out.

With **the same settings**, I've swapped grunt-shell with grunt-exec, and I started seeing the output.... so it's specific to grunt-shell.

Cheers.

**Comment by felquis** [comment]
Sorry for commenting in a old issue @sindresorhus 

I'm running `git clone` with this task,

```js

shell: {
  options: {
    stderr: true, // default
    stdout: true, // default
    stdin: true
  },
  cloneRepo: {
    command: [
      'git clone url'
    ].join('&&')
  }
}
```

When I use `git clone` it shows me a progress, but with this task it doesn't show any progress message.

Seems like the same issue @Thinkscape ran into. 

But, if I test for example with `ls` it shows all the output.

I tried with `--no-color` flag, but with no change in the outputs.
