### ISSUE TITLE
Passing argument with a colon (like a URL)

### ISSUE THREAD

**Issue by runlevelsix** [sindresorhus/grunt-shell#87]
I'm at a loss for how to escape passing an argument into the shell command. I'm escaping with single quotes, double quotes, back ticks, backslash, etc and no matter how I pass the url, it always only see 'http' as the parameter.

I'm trying to run a `couchapp push` command

```javascript
dbPath = "http://user:pass@localhost:5984/" + clientData.webapp_config.db;
grunt.task.run('shell:pushdocs:' + webappPath + ':\''+ dbPath +'\'');
```

It always returns:
```shell
Running "shell:pushdocs:clientbuilds/webapp:'http://user:pass@localhost:5984/
estante-testing'" (shell) task
http
```

My setup for debugging is this:
```javascript
    grunt.initConfig({
        shell: {
            pushdocs: {
                command: function(webappPath, dbPath) {
                  return 'echo ' + dbPath + '\n';
                }
            }
        }
    });
```

Have I completely missed something about passing this URL in javascript?

**Comment by sindresorhus** [comment]
Use StackOverflow for support questions ;)
