### ISSUE TITLE
Each command failOnError callback ?

### ISSUE THREAD

**Issue by jianghai** [sindresorhus/grunt-shell#94]
I have multiple commands like
```js
shell: {
  multiple: {
    options: {
      failOnError: false,
      execOptions: {
        cwd: '../'
      }
    },
    command: [
      'git clone url',
      'git clone url'
    ].join(';')
  }
}
```
When clone the repro and destination already exists, I want to exec 'git pull', how could I do ?

**Comment by sindresorhus** [comment]
You can't have a callback for each command, as it's really just one command, you join them.

Easiest would probably be to just do the check in shell script, but that has nothing to do with this task and would be better asked on StackOverflow.
