### ISSUE TITLE
Git-command stuck

### ISSUE THREAD

**Issue by Jpunt** [sindresorhus/grunt-shell#95]
My shell gets stuck when running this command, but only sometimes:

```
commitVersion: {
  command: "git commit -am 'Release version <%= new_version %>' && git tag <%= new_version %> && git push && git push --tags",
},
```

`new_version` comes from task from [grunt-prompt](https://github.com/dylang/grunt-prompt). The weird thing is, the commands are actually executed (i've got a new commit with that message, a new tag, and everything is pushed), but my shell doesn't get the callback:

```
Running "prompt:release" (prompt) task
? Current version is 1.0.13, what version do you wanna release? 1.0.14

Running "replace:version" (replace) task

Running "shell:commitVersion" (shell) task
```

What can I try to fix this?

**Comment by clubdesign** [comment]
Same here.

Our Command executes `git flow feature start "feature_name"` and gets stuck although everything is done correctly.

Any fix?

**Comment by clubdesign** [comment]
@Jpunt After a quick test i suggest you to use grunt-exec in the meantime until this is fixed.
It works for us and the commands are the same.

**Comment by silverwind** [comment]
Also had a command getting stuck: `ncu -u` which is [npm-check-updates](https://github.com/tjunnone/npm-check-updates).

**Comment by silverwind** [comment]
Nevermind me, my issue seems with the module itself - https://github.com/tjunnone/npm-check-updates/issues/119

**Comment by zenopopovici** [comment]
Nope, it's a grunt-shell issue. Also `npm install` breaks. This could be the reason: https://github.com/tjunnone/npm-check-updates/issues/119

**Comment by silverwind** [comment]
I think the issue with `ncu` boils down to process.stdin.isTTY being `undefined` in processes spawned by `exec`, making `is-stdin` think there i something on stdin when there is not. `grunt-shell`'s attempt to pipe stdin (`process.stdin.pipe(cp.stdin)`) to the child is effortless because the exec command already has run by the point this pipe is attached.

I think the proper solution here would be to switch to `spawn` and define stdio stream handling inside the spawn option. Either that, or it's a node bug with `isTTY`.

**Comment by sindresorhus** [comment]
Closing as it seems it's a Node.js core problem and nothing we can do here.

**Comment by silverwind** [comment]
I think this should be fixed in this module or maybe a wrapper by calling `stdin.end()` on the ChildProcess. Any child process that waits on stdin will hang until stdin is explicitely closed:

https://nodejs.org/api/child_process.html#child_process_child_stdin
