### ISSUE TITLE
Invalid version: "0.5"

### ISSUE THREAD

**Issue by ebarolo** [sindresorhus/grunt-shell#96]
I can't install the grunt-shell 

here the error log 

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'grunt-shell' ]
2 info using npm@2.7.3
3 info using node@v0.12.0
4 verbose stack Error: Invalid version: "0.5"
4 verbose stack     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:190:13)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:368:33)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:127:33)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:267:40
4 verbose stack     at evalmachine.<anonymous>:336:14
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
4 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
5 verbose cwd /Volumes/Storage 2/Dev_APP/LongBoard/LongBoard_NativeApp
6 error Darwin 14.3.0
7 error argv "node" "/usr/local/bin/npm" "install" "--save-dev" "grunt-shell"
8 error node v0.12.0
9 error npm  v2.7.3
10 error Invalid version: "0.5"
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by arthurvr** [comment]
> 11 error If you need help, you may report this error at:
11 error https://github.com/npm/npm/issues
